name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-15
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu 1.6.9 SDK
        run: |
          curl -fL https://github.com/acidanthera/Lilu/releases/download/1.6.9/Lilu-1.6.9-DEBUG.zip -o /tmp/Lilu.zip
          unzip -q /tmp/Lilu.zip

      - run: xcodebuild -jobs 1 -target WMIDellSensors -configuration Release -arch x86_64 MACOSX_DEPLOYMENT_TARGET=10.13
      - run: xcodebuild -jobs 1 -target wmitool -configuration Release -arch x86_64 MACOSX_DEPLOYMENT_TARGET=10.13

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            build/Release/WMIDellSensors.kext
            build/Release/wmitool
